version: "3"
services:
  app-api:
    build:
      context: "./app-api"
      dockerfile: "./${NODE_ENV}/Dockerfile"
    container_name: "app-api"
    ports: 
      - "${PORT_API}:${PORT_API}"
    volumes:
      - "./app-api/src:/app-api/src"
    env_file:
      - ".env"
  db-mysql:
    build:
      context: "./db-mysql"
      dockerfile: "Dockerfile"
    container_name: "db-mysql"
    ports: 
      - "${PORT_MYSQL}:${PORT_MYSQL}"
    env_file:
      - ".env"